### ISSUE TITLE
Inchworm compilation problem

### ISSUE THREAD

**Issue by noncodo** [trinityrnaseq/trinityrnaseq#73]
I'm having issues compiling Inchworm on a SUSE server. I thought that any gcc above 4.3 would suffice. Any ideas? 

$cat /etc/issue
Welcome to SUSE Linux Enterprise Server 11 SP3  (x86_64) - Kernel \r (\l).

$uname -a
Linux servername 3.0.76-0.11-default #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) x86_64 x86_64 x86_64 GNU/Linux

$gcc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux)

trinityrnaseq$ make
[...]
 g++ -DHAVE_CONFIG_H -I. -I..    -ansi -pedantic -fopenmp -Wall -Wextra -Wno-deprecated -m64 -g -O2 -MT IRKE_run.o -MD -MP -MF .deps/IRKE_run.Tpo -c -o IRKE_run.o IRKE_run.cpp
In file included from IRKE.hpp:6,
                 from IRKE_run.cpp:11:
sequenceUtil.hpp:20: error: ISO C++ 1998 does not support ‘long long’
sequenceUtil.hpp:46: error: ISO C++ 1998 does not support ‘long long’
make[2]: *** [IRKE_run.o] Error 1
make[2]: Leaving directory `/programs/trinityrnaseq/Inchworm/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/programs/trinityrnaseq/Inchworm'
make: *** [inchworm_target] Error 2

**Comment by noncodo** [comment]
Works with a GCC > 4.3. Perhaps this should be mentioned somewhere in the installation readme?
